"""initial

Revision ID: d15df687f808
Revises: 
Create Date: 2026-03-23 16:06:15.817923

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d15df687f808"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("users",
    sa.Column("telegram_id", sa.BigInteger(), nullable=False, comment="Telegram ID пользователя"),
    sa.Column("username", sa.String(length=64), nullable=True, comment="Юзернейм пользователя в Telegram"),
    sa.Column("display_name", sa.String(length=128), nullable=True, comment="Отображаемое имя пользователя"),
    sa.Column("description", sa.Text(), nullable=True, comment="Описание профиля пользователя"),
    sa.Column("avatar_url", sa.String(length=512), nullable=True, comment="URL аватара пользователя"),
    sa.Column("role", sa.String(length=16), nullable=True, comment="Роль пользователя: streamer | viewer | null"),
    sa.Column("balance", sa.BigInteger(), server_default="0", nullable=False, comment="Баланс пользователя в монетах"),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("telegram_id"),
    )
    op.create_table("alert_settings",
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="ID правила доната в OBS виджете"),
    sa.Column("streamer_id", sa.BigInteger(), nullable=False, comment="ID стримера, которому принадлежат правила доната"),
    sa.Column("bg_color", sa.String(length=16), server_default="#1a1a2e", nullable=False, comment="Фоновый цвет доната"),
    sa.Column("text_color", sa.String(length=16), server_default="#ffffff", nullable=False, comment="Цвет текста доната"),
    sa.Column("font", sa.String(length=64), server_default="Roboto", nullable=False, comment="Шрифт доната"),
    sa.Column("duration_sec", sa.Integer(), server_default="5", nullable=False, comment="Длительность доната"),
    sa.Column("image_enabled", sa.Boolean(), server_default="true", nullable=False, comment="Флаг включения пикчи в донате"),
    sa.Column("tts_enabled", sa.Boolean(), server_default="true", nullable=False, comment="Флаг включения озвучки доната"),
    sa.Column("tts_voice", sa.String(length=64), server_default="silero_v3_ru", nullable=False, comment="Голос озвучки доната"),
    sa.ForeignKeyConstraint(["streamer_id"], ["users.telegram_id"], ),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("streamer_id"),
    )
    op.create_table("passive_income_settings",
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="ID настроек пассивного дохода"),
    sa.Column("streamer_id", sa.BigInteger(), nullable=False, comment="ID стримера, которому принадлежат настройки"),
    sa.Column("enabled", sa.Boolean(), server_default="false", nullable=False, comment="Флаг включения пассивного дохода"),
    sa.Column("coins_per_interval", sa.Integer(), server_default="10", nullable=False, comment="Количество монет, начисляемых за интервал"),
    sa.Column("interval_minutes", sa.Integer(), server_default="5", nullable=False, comment="Интервал начисления монет в минутах"),
    sa.ForeignKeyConstraint(["streamer_id"], ["users.telegram_id"], ),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("streamer_id"),
    )
    op.create_table("stop_words",
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="ID стоп-слова"),
    sa.Column("streamer_id", sa.BigInteger(), nullable=False, comment="ID стримера, которому принадлежит стоп-слово"),
    sa.Column("word", sa.String(length=128), nullable=False, comment="Стоп-слово для фильтрации донатов"),
    sa.ForeignKeyConstraint(["streamer_id"], ["users.telegram_id"], ),
    sa.PrimaryKeyConstraint("id"),
    )
    op.create_table("stream_goals",
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="ID цели стрима"),
    sa.Column("streamer_id", sa.BigInteger(), nullable=False, comment="ID стримера, которому принадлежит цель"),
    sa.Column("title", sa.String(length=256), nullable=True, comment="Название цели стрима"),
    sa.Column("target_amount", sa.BigInteger(), server_default="0", nullable=False, comment="Целевая сумма в монетах"),
    sa.Column("current_amount", sa.BigInteger(), server_default="0", nullable=False, comment="Текущая набранная сумма в монетах"),
    sa.ForeignKeyConstraint(["streamer_id"], ["users.telegram_id"], ),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("streamer_id"),
    )
    op.create_table("stream_sessions",
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="ID стрим-сессии"),
    sa.Column("streamer_id", sa.BigInteger(), nullable=False, comment="ID стримера, которому принадлежит сессия"),
    sa.Column("stream_token", sa.String(length=64), nullable=False, comment="Уникальный токен стрим-сессии для OBS-виджета"),
    sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False, comment="Флаг активности стрим-сессии"),
    sa.Column("passive_income_enabled", sa.Boolean(), server_default="false", nullable=False, comment="Флаг включения пассивного дохода для зрителей во время стрима"),
    sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False, comment="Дата и время начала стрима"),
    sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True, comment="Дата и время окончания стрима"),
    sa.ForeignKeyConstraint(["streamer_id"], ["users.telegram_id"], ),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("stream_token"),
    )
    op.create_table("donations",
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="ID доната"),
    sa.Column("from_user_id", sa.BigInteger(), nullable=False, comment="ID пользователя, отправившего донат"),
    sa.Column("to_streamer_id", sa.BigInteger(), nullable=False, comment="ID стримера, получившего донат"),
    sa.Column("session_id", sa.BigInteger(), nullable=False, comment="ID стрим-сессии, в которой был отправлен донат"),
    sa.Column("amount", sa.BigInteger(), nullable=False, comment="Сумма доната в монетах"),
    sa.Column("message", sa.Text(), nullable=True, comment="Сообщение к донату"),
    sa.Column("status", sa.String(length=16), nullable=False, comment="Статус доната: processing | delivered | rejected"),
    sa.Column("reject_reason", sa.String(length=16), nullable=True, comment="Причина отклонения доната: toxicity | stopword | nsfw | null"),
    sa.Column("audio_url", sa.String(length=512), nullable=True, comment="URL аудио TTS-озвучки доната"),
    sa.Column("image_url", sa.String(length=512), nullable=True, comment="URL картинки к донату"),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False, comment="Дата и время создания доната"),
    sa.ForeignKeyConstraint(["from_user_id"], ["users.telegram_id"], ),
    sa.ForeignKeyConstraint(["session_id"], ["stream_sessions.id"], ),
    sa.ForeignKeyConstraint(["to_streamer_id"], ["users.telegram_id"], ),
    sa.PrimaryKeyConstraint("id"),
    )
    op.create_table("balance_transactions",
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="ID транзакции"),
    sa.Column("user_id", sa.BigInteger(), nullable=False, comment="ID пользователя, которому принадлежит транзакция"),
    sa.Column("amount", sa.BigInteger(), nullable=False, comment="Сумма транзакции в монетах (отрицательная при списании)"),
    sa.Column("type", sa.String(length=32), nullable=False, comment="Тип транзакции: topup | donation_sent | donation_received | passive_income | initial"),
    sa.Column("ref_donation_id", sa.BigInteger(), nullable=True, comment="ID доната, с которым связана транзакция (если применимо)"),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False, comment="Дата и время создания транзакции"),
    sa.ForeignKeyConstraint(["ref_donation_id"], ["donations.id"], ),
    sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ),
    sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("balance_transactions")
    op.drop_table("donations")
    op.drop_table("stream_sessions")
    op.drop_table("stream_goals")
    op.drop_table("stop_words")
    op.drop_table("passive_income_settings")
    op.drop_table("alert_settings")
    op.drop_table("users")
    # ### end Alembic commands ###
