"""add display name custom to users

Revision ID: 9370bad7e785
Revises: d15df687f808
Create Date: 2026-04-06 23:00:27.500735

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9370bad7e785"
down_revision: str | Sequence[str] | None = "d15df687f808"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column(
		"users",
		sa.Column(
			"display_name_custom",
			sa.Boolean(),
			server_default="false",
			nullable=False,
			comment="True если пользователь явно задал display_name через API",
		),
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column("users", "display_name_custom")
	# ### end Alembic commands ###
